version: "2"

services:

  api:
    container_name: "express-whiteapp"
    image: "node:latest"
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - "mongo"
    command: "bash -c 'npm install && npm start'"
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "MONGODB_CONNECTION_URL=mongodb://mongo:27017/whiteapp"

  mongo:
    image: "mongo:latest"
    volumes:
      - "$HOME/docker/volumes/mongodb:/data/db"
    expose:
      - "27017"
